---
  - name: Save S3 Buckets
    set_fact:
      bucket_name_list: "{{ kentik_bucket.stack_resources.0.physical_resource_id }}"
    listen: finished_aws
    when: not s3_flowlogs_bucket
    loop_control:
      label: "{{ kentik_bucket.stack_resources.0.physical_resource_id if not s3_flowlogs_bucket else s3_flowlogs_bucket }}"

  - name: Inform of Results
    listen: finished_aws
    debug:
      msg: [
        "S3 Buckets Name: {{ bucket_name_list if not s3_flowlogs_bucket else s3_flowlogs_bucket }}",
        "IAM Role ARN: {{ kentik_role.arn }}"
      ]
