---
  - name: Configure Flow Logs for VPCs
    cloudformation:
      stack_name: "{{ '-'.join((item, 'flow-logs')) }}"
      template_body: "{{ lookup ('template', 'aws_vpc_flow_logs.j2') |string }}"
      template_parameters:
        ResourceId: "{{ item }}"
        MaxAggregationInterval: "{{ '60' if store_logs_more_frequently else '600' }}"
      on_create_failure: "DELETE"
      state: 'present'
    notify: finished_aws
    with_items: "{{ vpc_id_list | mandatory }}"
