---
  - name: Prepare the S3 Bucket Path
    set_fact:
      s3_bucket_path: "{{ s3_bucket_path | regex_replace('^\\/|\\/$', '')}}"

  - name: Create EC2 Access Policy
    iam_managed_policy:
      policy_name: "{{ iam_role_prefix }}EC2Access"
      policy: "{{ lookup('file', 'aws_iam_ec2_access_policy.json') }}"
      policy_description: "Defines required accesses for Kentik platform to EC2 resources"
      state: present

  - name: Create S3 Access Policy
    iam_managed_policy:
      policy_name: "{{ iam_role_prefix }}S3Access"
      policy: "{{ lookup('template', 'aws_iam_s3_access_policy.j2') }}"
      policy_description: "Defines accesses for Kentik platform to S3 resources"
      state: present

  - name: Create Kentik Role
    iam_role:
      name: "{{ iam_role_prefix }}AnsibleIngestRole"
      assume_role_policy_document: "{{ lookup('file', 'aws_iam_role.json') }}"
      managed_policy:
      - "{{ iam_role_prefix }}EC2Access"
      - "{{ iam_role_prefix }}S3Access"
      description: "This role allows Kentik to ingest the VPC flow logs"
      state: present
    register: kentik_role
